# Generated by Django 5.1.7 on 2025-03-30 02:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_alter_threat_severity_alter_threat_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threat',
            name='description',
        ),
        migrations.AddField(
            model_name='threat',
            name='details',
            field=models.TextField(default='No details provided', help_text='Detailed information about the detected threat.'),
        ),
        migrations.AddField(
            model_name='threat',
            name='reported_by',
            field=models.CharField(blank=True, help_text='Source reporting the threat (e.g., system module or admin).', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='threat',
            name='source_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP address of the attacker or source.', null=True),
        ),
        migrations.AddField(
            model_name='threat',
            name='user_agent',
            field=models.CharField(blank=True, help_text="User agent of the attacker's device.", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='threat',
            name='detected_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the threat was detected.'),
        ),
        migrations.AlterField(
            model_name='threat',
            name='severity',
            field=models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Low', help_text='Threat severity level.', max_length=50),
        ),
        migrations.AlterField(
            model_name='threat',
            name='type',
            field=models.CharField(help_text='Type of detected threat (e.g., SQL Injection, XSS).', max_length=255),
        ),
    ]
