# Generated by Django 5.1.7 on 2025-03-30 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_remove_threat_description_threat_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threat',
            name='type',
        ),
        migrations.AddField(
            model_name='threat',
            name='threat_type',
            field=models.CharField(default='Unknown Threat', help_text='Type of detected threat (e.g., SQL Injection, XSS, Phishing).', max_length=255),
        ),
        migrations.AlterField(
            model_name='threat',
            name='reported_by',
            field=models.CharField(blank=True, help_text='Source reporting the threat (e.g., system module, admin, automated detector).', max_length=255, null=True),
        ),
    ]
